version: '3.8'
services:
  cmake2:
    container_name: pfe
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - './src:/src'
      - '/var/run/docker.sock:/var/run/docker.sock'
    tty: true