version: '3.8'
services:
  machine:
    build:
      context: .
      dockerfile: Dockerfile  
    restart: always
    volumes:
      - './src:/src'
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker    
    tty: true
    networks:
      - swarm-gen      
networks:
  swarm-gen: